name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Meadow.Units
    - name: Build and package
      run: dotnet build --configuration Release --no-restore Source/Meadow.Units/Meadow.Units.sln
    # - name: Package library
    #   run: dotnet pack Source/Meadow.Units/Meadow.Units.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal Source/Meadow.Units/Meadow.Units.sln
    - name: Upload package as Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: Meadow.Units
        path: Source/Meadow.Units/bin/Release/*.nupkg
